-- CO-LAB CONNECT Supabase PostgreSQL schema
-- Run this file in Supabase SQL Editor. It is safe to run more than once.

create extension if not exists pgcrypto;

create table if not exists users (
  id bigint generated by default as identity primary key,
  auth_user_id uuid unique,
  email text unique,
  phone varchar(20) not null unique,
  name varchar(255) not null,
  password_hash varchar(255) not null,
  role text not null default 'customer' check (role in ('customer','worker','cooperative_admin','federation_admin','platform_admin')),
  is_active boolean not null default true,
  is_verified boolean not null default false,
  language_preference varchar(10) not null default 'en',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists federations (
  id bigint generated by default as identity primary key,
  name varchar(255) not null,
  description text,
  contact_email text,
  contact_phone varchar(20),
  admin_user_id bigint references users(id) on delete set null,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists cooperatives (
  id bigint generated by default as identity primary key,
  name varchar(255) not null,
  registration_number varchar(100) unique,
  contact_email text,
  contact_phone varchar(20),
  address text,
  latitude double precision,
  longitude double precision,
  service_area_km double precision not null default 25,
  admin_user_id bigint references users(id) on delete set null,
  federation_id bigint references federations(id) on delete set null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists service_categories (
  id bigint generated by default as identity primary key,
  name varchar(255) not null,
  slug varchar(255) not null unique,
  description text,
  icon varchar(255),
  is_active boolean not null default true,
  display_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists services (
  id bigint generated by default as identity primary key,
  category_id bigint not null references service_categories(id) on delete restrict,
  name varchar(255) not null,
  slug varchar(255) not null unique,
  description text,
  required_skills jsonb,
  optional_qualifications jsonb,
  verification_required boolean not null default false,
  availability_type varchar(50) not null default 'on_demand',
  location_rule varchar(50) not null default 'at_customer',
  emergency_support boolean not null default false,
  base_price numeric(12,2),
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists skills (
  id bigint generated by default as identity primary key,
  name varchar(255) not null,
  slug varchar(255) not null unique,
  category_id bigint references service_categories(id) on delete set null,
  description text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists workers (
  id bigint generated by default as identity primary key,
  user_id bigint not null unique references users(id) on delete cascade,
  cooperative_id bigint references cooperatives(id) on delete set null,
  name varchar(255) not null,
  phone varchar(20) not null,
  email text,
  latitude double precision,
  longitude double precision,
  service_area_km double precision not null default 10,
  verification_status text not null default 'pending' check (verification_status in ('pending','verified','rejected')),
  verification_date timestamptz,
  verification_notes text,
  profile_photo text,
  experience_years integer not null default 0 check (experience_years >= 0),
  current_workload integer not null default 0 check (current_workload >= 0),
  max_workload integer not null default 5 check (max_workload > 0),
  is_available boolean not null default true,
  total_completed_services integer not null default 0 check (total_completed_services >= 0),
  average_rating numeric(3,2) not null default 0 check (average_rating between 0 and 5),
  bio text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists worker_skills (
  id bigint generated by default as identity primary key,
  worker_id bigint not null references workers(id) on delete cascade,
  skill_id bigint not null references skills(id) on delete cascade,
  proficiency text not null default 'intermediate' check (proficiency in ('beginner','intermediate','expert')),
  years_experience integer not null default 0,
  is_verified boolean not null default false,
  created_at timestamptz not null default now(),
  unique(worker_id, skill_id)
);

create table if not exists availability (
  id bigint generated by default as identity primary key,
  worker_id bigint not null references workers(id) on delete cascade,
  day_of_week smallint not null check (day_of_week between 0 and 6),
  start_time time not null,
  end_time time not null,
  is_available boolean not null default true,
  effective_from date,
  effective_until date,
  created_at timestamptz not null default now(),
  check (end_time > start_time)
);

create table if not exists worker_certifications (
  id bigint generated by default as identity primary key,
  worker_id bigint not null references workers(id) on delete cascade,
  skill_id bigint references skills(id) on delete set null,
  certification_name varchar(255) not null,
  issuing_authority varchar(255) not null,
  issue_date date,
  expiry_date date,
  document_url text,
  verification_status text not null default 'pending' check (verification_status in ('pending','verified','rejected')),
  verified_by bigint references users(id) on delete set null,
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists service_requests (
  id bigint generated by default as identity primary key,
  customer_id bigint not null references users(id) on delete restrict,
  service_id bigint not null references services(id) on delete restrict,
  cooperative_id bigint references cooperatives(id) on delete set null,
  description text,
  location_address varchar(500),
  location_lat double precision,
  location_lng double precision,
  preferred_date date,
  preferred_time_start time,
  preferred_time_end time,
  urgency varchar(20) not null default 'normal' check (urgency in ('low','normal','medium','high','urgent')),
  special_requirements jsonb,
  status varchar(30) not null default 'pending',
  allocated_worker_id bigint references workers(id) on delete set null,
  allocation_id bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (preferred_time_end is null or preferred_time_start is null or preferred_time_end > preferred_time_start)
);

create table if not exists allocations (
  id bigint generated by default as identity primary key,
  request_id bigint not null references service_requests(id) on delete cascade,
  worker_id bigint not null references workers(id) on delete restrict,
  cooperative_id bigint not null references cooperatives(id) on delete restrict,
  admin_user_id bigint not null references users(id) on delete restrict,
  recommendation_score numeric(8,5),
  allocation_reason text,
  status varchar(30) not null default 'recommended',
  allocated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

alter table service_requests
  drop constraint if exists service_requests_allocation_id_fkey;
alter table service_requests
  add constraint service_requests_allocation_id_fkey
  foreign key (allocation_id) references allocations(id) on delete set null;

create table if not exists bookings (
  id bigint generated by default as identity primary key,
  request_id bigint not null references service_requests(id) on delete restrict,
  allocation_id bigint references allocations(id) on delete set null,
  worker_id bigint not null references workers(id) on delete restrict,
  customer_id bigint not null references users(id) on delete restrict,
  cooperative_id bigint not null references cooperatives(id) on delete restrict,
  service_date date,
  time_start time,
  time_end time,
  status varchar(30) not null default 'confirmed',
  actual_start timestamptz,
  actual_end timestamptz,
  total_amount numeric(12,2),
  material_charges numeric(12,2) not null default 0,
  final_amount numeric(12,2),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists payments (
  id bigint generated by default as identity primary key,
  booking_id bigint not null references bookings(id) on delete cascade,
  amount numeric(12,2) not null check (amount >= 0),
  payment_method varchar(50),
  transaction_reference varchar(255) unique,
  status varchar(30) not null default 'pending',
  paid_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists invoices (
  id bigint generated by default as identity primary key,
  booking_id bigint not null unique references bookings(id) on delete cascade,
  invoice_number varchar(50) not null unique,
  service_charges numeric(12,2),
  material_charges numeric(12,2),
  commission_amount numeric(12,2),
  welfare_amount numeric(12,2),
  worker_payout numeric(12,2),
  total_amount numeric(12,2),
  tax_amount numeric(12,2),
  net_amount numeric(12,2),
  payment_status varchar(30) not null default 'pending',
  issued_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists ratings (
  id bigint generated by default as identity primary key,
  booking_id bigint not null unique references bookings(id) on delete cascade,
  customer_id bigint not null references users(id) on delete restrict,
  worker_id bigint not null references workers(id) on delete restrict,
  rating smallint not null check (rating between 1 and 5),
  feedback text,
  service_quality smallint check (service_quality between 1 and 5),
  punctuality smallint check (punctuality between 1 and 5),
  professionalism smallint check (professionalism between 1 and 5),
  created_at timestamptz not null default now()
);

create table if not exists notifications (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  title varchar(255) not null,
  message text,
  type varchar(50),
  reference_type varchar(50),
  reference_id bigint,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists service_history (
  id bigint generated by default as identity primary key,
  customer_id bigint not null references users(id) on delete restrict,
  worker_id bigint not null references workers(id) on delete restrict,
  cooperative_id bigint not null references cooperatives(id) on delete restrict,
  booking_id bigint not null unique references bookings(id) on delete restrict,
  service_name varchar(255),
  service_date date,
  amount numeric(12,2),
  rating smallint check (rating between 1 and 5),
  created_at timestamptz not null default now()
);

create table if not exists welfare_records (
  id bigint generated by default as identity primary key,
  worker_id bigint not null references workers(id) on delete cascade,
  scheme_name varchar(255),
  provider varchar(255),
  enrollment_status varchar(50) not null default 'pending',
  coverage_details text,
  start_date date,
  end_date date,
  emergency_contact varchar(255),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists disputes (
  id bigint generated by default as identity primary key,
  booking_id bigint references bookings(id) on delete set null,
  raised_by bigint not null references users(id) on delete restrict,
  against_user_id bigint references users(id) on delete set null,
  cooperative_id bigint references cooperatives(id) on delete set null,
  category varchar(80) not null,
  description text not null,
  status varchar(30) not null default 'open',
  resolution text,
  resolved_by bigint references users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists incentives (
  id bigint generated by default as identity primary key,
  worker_id bigint references workers(id) on delete cascade,
  cooperative_id bigint references cooperatives(id) on delete cascade,
  name varchar(255) not null,
  description text,
  amount numeric(12,2) not null default 0,
  status varchar(30) not null default 'pending',
  earned_at timestamptz,
  paid_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists demand_records (
  id bigint generated by default as identity primary key,
  service_id bigint not null references services(id) on delete restrict,
  cooperative_id bigint not null references cooperatives(id) on delete restrict,
  region varchar(255),
  latitude double precision,
  longitude double precision,
  request_count integer not null default 0,
  fulfilled_count integer not null default 0,
  unmet_count integer not null default 0,
  avg_response_time double precision,
  period_start date,
  period_end date,
  created_at timestamptz not null default now()
);

create table if not exists material_requirements (
  id bigint generated by default as identity primary key,
  booking_id bigint not null references bookings(id) on delete cascade,
  worker_id bigint not null references workers(id) on delete restrict,
  item_name varchar(255) not null,
  description text,
  quantity integer not null default 1,
  estimated_cost numeric(12,2),
  status varchar(30) not null default 'pending',
  notes text,
  created_at timestamptz not null default now()
);

create index if not exists idx_workers_cooperative on workers(cooperative_id);
create index if not exists idx_workers_verification_availability on workers(verification_status, is_available);
create index if not exists idx_worker_skills_worker on worker_skills(worker_id);
create index if not exists idx_worker_skills_skill on worker_skills(skill_id);
create index if not exists idx_availability_worker_day on availability(worker_id, day_of_week, is_available);
create index if not exists idx_services_category on services(category_id);
create index if not exists idx_requests_customer on service_requests(customer_id, created_at desc);
create index if not exists idx_requests_cooperative_status on service_requests(cooperative_id, status, created_at desc);
create index if not exists idx_requests_service on service_requests(service_id);
create index if not exists idx_allocations_request on allocations(request_id, status);
create index if not exists idx_allocations_worker on allocations(worker_id, status);
create index if not exists idx_bookings_customer on bookings(customer_id, created_at desc);
create index if not exists idx_bookings_worker on bookings(worker_id, status, created_at desc);
create index if not exists idx_bookings_cooperative on bookings(cooperative_id, status);
create index if not exists idx_payments_booking on payments(booking_id, status);
create index if not exists idx_notifications_user_unread on notifications(user_id, is_read, created_at desc);
create index if not exists idx_history_customer on service_history(customer_id, created_at desc);
create index if not exists idx_history_worker on service_history(worker_id, created_at desc);
create index if not exists idx_demand_cooperative_period on demand_records(cooperative_id, period_start, period_end);

create or replace function set_updated_at() returns trigger
language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists users_updated_at on users;
create trigger users_updated_at before update on users for each row execute function set_updated_at();
drop trigger if exists cooperatives_updated_at on cooperatives;
create trigger cooperatives_updated_at before update on cooperatives for each row execute function set_updated_at();
drop trigger if exists workers_updated_at on workers;
create trigger workers_updated_at before update on workers for each row execute function set_updated_at();
drop trigger if exists service_requests_updated_at on service_requests;
create trigger service_requests_updated_at before update on service_requests for each row execute function set_updated_at();
drop trigger if exists bookings_updated_at on bookings;
create trigger bookings_updated_at before update on bookings for each row execute function set_updated_at();
drop trigger if exists welfare_updated_at on welfare_records;
create trigger welfare_updated_at before update on welfare_records for each row execute function set_updated_at();
drop trigger if exists disputes_updated_at on disputes;
create trigger disputes_updated_at before update on disputes for each row execute function set_updated_at();

-- RLS identity mapping: link a Supabase Auth user to public.users.auth_user_id.
create schema if not exists app;
create or replace function app.current_user_id() returns bigint
language sql stable security definer set search_path = public
as $$ select id from users where auth_user_id = auth.uid() limit 1 $$;
create or replace function app.current_role() returns text
language sql stable security definer set search_path = public
as $$ select role from users where id = app.current_user_id() $$;
create or replace function app.is_admin() returns boolean
language sql stable security definer set search_path = public
as $$ select coalesce(app.current_role() in ('platform_admin','federation_admin','cooperative_admin'), false) $$;

alter table users enable row level security;
alter table federations enable row level security;
alter table cooperatives enable row level security;
alter table service_categories enable row level security;
alter table services enable row level security;
alter table skills enable row level security;
alter table workers enable row level security;
alter table worker_skills enable row level security;
alter table availability enable row level security;
alter table worker_certifications enable row level security;
alter table service_requests enable row level security;
alter table allocations enable row level security;
alter table bookings enable row level security;
alter table payments enable row level security;
alter table invoices enable row level security;
alter table ratings enable row level security;
alter table notifications enable row level security;
alter table service_history enable row level security;
alter table welfare_records enable row level security;
alter table disputes enable row level security;
alter table incentives enable row level security;
alter table demand_records enable row level security;
alter table material_requirements enable row level security;

-- Public catalog reads. Backend/service-role connections bypass RLS.
 drop policy if exists catalog_read on service_categories;
 create policy catalog_read on service_categories for select using (is_active);
 drop policy if exists services_read on services;
 create policy services_read on services for select using (is_active);
 drop policy if exists skills_read on skills;
 create policy skills_read on skills for select using (is_active);

-- Users and organization visibility.
drop policy if exists users_self_or_admin on users;
create policy users_self_or_admin on users for select using (id = app.current_user_id() or app.is_admin());
drop policy if exists federations_members on federations;
create policy federations_members on federations for select using (app.current_user_id() is not null);
drop policy if exists cooperatives_members on cooperatives;
create policy cooperatives_members on cooperatives for select using (app.current_user_id() is not null);
drop policy if exists workers_members on workers;
create policy workers_members on workers for select using (
  user_id = app.current_user_id()
  or app.current_role() in ('platform_admin','federation_admin')
  or cooperative_id in (select id from cooperatives where admin_user_id = app.current_user_id())
);
drop policy if exists workers_self_or_admin_update on workers;
create policy workers_self_or_admin_update on workers for update using (
  user_id = app.current_user_id()
  or app.current_role() in ('platform_admin','federation_admin')
  or cooperative_id in (select id from cooperatives where admin_user_id = app.current_user_id())
);

-- Customer -> request -> booking -> worker -> payment -> rating.
drop policy if exists requests_access on service_requests;
create policy requests_access on service_requests for all using (
  customer_id = app.current_user_id()
  or app.current_role() in ('platform_admin','federation_admin')
  or cooperative_id in (select id from cooperatives where admin_user_id = app.current_user_id())
) with check (customer_id = app.current_user_id() or app.is_admin());
drop policy if exists allocations_access on allocations;
create policy allocations_access on allocations for all using (
  worker_id in (select id from workers where user_id = app.current_user_id())
  or cooperative_id in (select id from cooperatives where admin_user_id = app.current_user_id())
  or app.current_role() in ('platform_admin','federation_admin')
) with check (app.is_admin());
drop policy if exists bookings_access on bookings;
create policy bookings_access on bookings for all using (
  customer_id = app.current_user_id()
  or worker_id in (select id from workers where user_id = app.current_user_id())
  or cooperative_id in (select id from cooperatives where admin_user_id = app.current_user_id())
  or app.current_role() in ('platform_admin','federation_admin')
) with check (customer_id = app.current_user_id() or app.is_admin());
drop policy if exists payments_access on payments;
create policy payments_access on payments for all using (
  booking_id in (select id from bookings where customer_id = app.current_user_id() or worker_id in (select id from workers where user_id = app.current_user_id()) or cooperative_id in (select id from cooperatives where admin_user_id = app.current_user_id()))
  or app.current_role() in ('platform_admin','federation_admin')
) with check (app.is_admin() or booking_id in (select id from bookings where customer_id = app.current_user_id()));
drop policy if exists invoices_access on invoices;
create policy invoices_access on invoices for select using (booking_id in (select id from bookings where customer_id = app.current_user_id() or worker_id in (select id from workers where user_id = app.current_user_id()) or cooperative_id in (select id from cooperatives where admin_user_id = app.current_user_id())) or app.is_admin());
drop policy if exists ratings_access on ratings;
create policy ratings_access on ratings for all using (customer_id = app.current_user_id() or worker_id in (select id from workers where user_id = app.current_user_id()) or app.is_admin()) with check (customer_id = app.current_user_id());

-- Worker/cooperative operational data.
drop policy if exists worker_skills_access on worker_skills;
create policy worker_skills_access on worker_skills for all using (worker_id in (select id from workers where user_id = app.current_user_id()) or app.is_admin()) with check (worker_id in (select id from workers where user_id = app.current_user_id()) or app.is_admin());
drop policy if exists availability_access on availability;
create policy availability_access on availability for all using (worker_id in (select id from workers where user_id = app.current_user_id()) or app.is_admin()) with check (worker_id in (select id from workers where user_id = app.current_user_id()) or app.is_admin());
drop policy if exists certification_access on worker_certifications;
create policy certification_access on worker_certifications for all using (worker_id in (select id from workers where user_id = app.current_user_id()) or app.is_admin()) with check (worker_id in (select id from workers where user_id = app.current_user_id()) or app.is_admin());
drop policy if exists notifications_own on notifications;
create policy notifications_own on notifications for all using (user_id = app.current_user_id()) with check (user_id = app.current_user_id());
drop policy if exists history_access on service_history;
create policy history_access on service_history for select using (customer_id = app.current_user_id() or worker_id in (select id from workers where user_id = app.current_user_id()) or app.is_admin());
drop policy if exists welfare_access on welfare_records;
create policy welfare_access on welfare_records for all using (worker_id in (select id from workers where user_id = app.current_user_id()) or app.is_admin()) with check (worker_id in (select id from workers where user_id = app.current_user_id()) or app.is_admin());
drop policy if exists disputes_access on disputes;
create policy disputes_access on disputes for all using (raised_by = app.current_user_id() or against_user_id = app.current_user_id() or app.is_admin()) with check (raised_by = app.current_user_id() or app.is_admin());
drop policy if exists incentives_access on incentives;
create policy incentives_access on incentives for select using (worker_id in (select id from workers where user_id = app.current_user_id()) or app.is_admin());
drop policy if exists demand_admin_access on demand_records;
create policy demand_admin_access on demand_records for select using (app.is_admin());
drop policy if exists material_access on material_requirements;
create policy material_access on material_requirements for all using (worker_id in (select id from workers where user_id = app.current_user_id()) or booking_id in (select id from bookings where customer_id = app.current_user_id()) or app.is_admin()) with check (worker_id in (select id from workers where user_id = app.current_user_id()) or app.is_admin());

-- Realistic demo data. Passwords are only for local/demo use.
insert into users (email, phone, name, password_hash, role, is_active, is_verified)
values
  ('customer@demo.com', '9000000101', 'Customer Demo', crypt('CoLab!Demo2026', gen_salt('bf')), 'customer', true, true),
  ('worker@demo.com', '9000000102', 'Worker Demo', crypt('CoLab!Demo2026', gen_salt('bf')), 'worker', true, true),
  ('coop@demo.com', '9000000103', 'Cooperative Admin Demo', crypt('CoLab!Demo2026', gen_salt('bf')), 'cooperative_admin', true, true),
  ('federation@demo.com', '9000000104', 'Federation Admin Demo', crypt('CoLab!Demo2026', gen_salt('bf')), 'federation_admin', true, true)
on conflict (email) do nothing;

insert into federations (name, description, contact_email, admin_user_id)
select 'CO-LAB Demo Federation', 'Federation for local worker cooperatives.', 'federation@demo.com', id from users
where email = 'federation@demo.com'
and not exists (select 1 from federations where name = 'CO-LAB Demo Federation');

insert into cooperatives (name, registration_number, contact_email, contact_phone, address, latitude, longitude, service_area_km, admin_user_id, federation_id)
select 'CO-LAB Demo Cooperative', 'COLAB-DEMO-001', 'coop@demo.com', '9000000103', 'Pune, Maharashtra', 18.5204, 73.8567, 25, u.id, f.id
from users u cross join federations f where u.email = 'coop@demo.com' and f.name = 'CO-LAB Demo Federation'
on conflict (registration_number) do nothing;

insert into service_categories (name, slug, description, is_active, display_order) values
  ('Home & Repair', 'home-repair', 'Trusted local repair services.', true, 1),
  ('Cleaning & Household', 'cleaning-household', 'Household support services.', true, 2)
on conflict (slug) do nothing;

insert into services (category_id, name, slug, description, required_skills, emergency_support, base_price)
select c.id, v.name, v.slug, v.description, v.required_skills::jsonb, v.emergency_support, v.base_price
from service_categories c cross join (values
  ('Plumber','plumber','Pipe repair, fixture installation, and leak detection.','["Pipe Repair","Fixture Installation","Leak Detection"]',true,750.00),
  ('Electrician','electrician','Electrical installation, repair, and maintenance.','["Electrical Wiring","Circuit Repair"]',true,800.00),
  ('Cleaner','cleaner','Professional home and office cleaning.','["Deep Cleaning","Surface Sanitization"]',false,500.00)
) as v(name, slug, description, required_skills, emergency_support, base_price)
where c.slug = 'home-repair' or (c.slug = 'cleaning-household' and v.slug = 'cleaner')
on conflict (slug) do nothing;

insert into skills (name, slug, description, category_id)
select v.name, v.slug, v.description, c.id from (values
  ('Pipe Repair','pipe-repair','Repair and replacement of plumbing pipes.','home-repair'),
  ('Fixture Installation','fixture-installation','Installation of faucets and fixtures.','home-repair'),
  ('Leak Detection','leak-detection','Detection and repair of water leaks.','home-repair'),
  ('Electrical Wiring','electrical-wiring','Residential and commercial wiring.','home-repair'),
  ('Circuit Repair','circuit-repair','Diagnosis and repair of circuits.','home-repair'),
  ('Deep Cleaning','deep-cleaning','Thorough cleaning of surfaces and rooms.','cleaning-household')
) v(name, slug, description, category_slug) join service_categories c on c.slug = v.category_slug
on conflict (slug) do nothing;

insert into workers (user_id, cooperative_id, name, phone, email, latitude, longitude, service_area_km, verification_status, experience_years, is_available, bio)
select u.id, c.id, u.name, u.phone, u.email, 18.5204, 73.8567, 25, 'verified', 5, true, 'Verified local service worker for the demo cooperative.'
from users u cross join cooperatives c where u.email = 'worker@demo.com' and c.registration_number = 'COLAB-DEMO-001'
on conflict (user_id) do nothing;

insert into worker_skills (worker_id, skill_id, proficiency, years_experience, is_verified)
select w.id, s.id, 'expert', 5, true from workers w cross join skills s
where w.email = 'worker@demo.com' and s.slug in ('pipe-repair','fixture-installation','leak-detection')
on conflict (worker_id, skill_id) do nothing;

insert into availability (worker_id, day_of_week, start_time, end_time, is_available)
select workers.id, days.day_of_week, '08:00', '18:00', true
from workers cross join generate_series(0, 6) as days(day_of_week)
where email = 'worker@demo.com'
and not exists (select 1 from availability a where a.worker_id = workers.id and a.day_of_week = days.day_of_week);

-- Enable Supabase Realtime publication for shared workflow tables.
do $$
declare
  table_name text;
begin
  foreach table_name in array array['service_requests','allocations','bookings','payments','notifications','demand_records'] loop
    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = table_name
    ) then
      execute format('alter publication supabase_realtime add table public.%I', table_name);
    end if;
  end loop;
end $$;
